-- Presence: last_active_at is touched by a deliberately narrow set of real
-- activity signals — the WS gateway's connect/heartbeat-pong/disconnect
-- (internal/realtime/websocket.go) and cmd/api's message-send/reaction/
-- read-state handlers (cmd/api/presence.go) — never by every authenticated
-- request, so read traffic never turns into write traffic against this
-- control-plane table.
--
-- is_online is never stored: it's derived at read time from how recent
-- this timestamp is (see internal/users.IsOnline/OnlineWindow), the same
-- "last seen" pattern most chat platforms use rather than maintaining a
-- distributed live-connection registry.
ALTER TABLE users ADD COLUMN last_active_at TIMESTAMPTZ;
