-- Adds a recoverable, at-rest-encrypted copy of an app credential's secret
-- alongside the existing secret_hash. The two columns serve different
-- purposes and neither replaces the other:
--
--   secret_hash      SHA-256, used by CredentialRepo.Verify on every
--                     Basic-auth request (POST /apps/token) — fast,
--                     constant-time comparable, and never needs decrypting.
--
--   secret_encrypted  AES-256-GCM ciphertext (internal/platform/secretbox),
--                     decryptable only by whoever holds
--                     APP_SECRET_ENCRYPTION_KEY. Exists solely so
--                     CredentialRepo.Reveal can hand a dashboard user their
--                     secret back after the one-time "created" response is
--                     gone (e.g. they closed the modal) — see
--                     GET /apps/{app_id}/credentials/{credential_id}/reveal.
--
-- Nullable because existing rows created before this migration have no
-- recoverable secret (only their hash survived) — Reveal returns "not
-- found" for those rather than a decryption error; a business that needs
-- one back simply rotates the credential.
ALTER TABLE app_credentials ADD COLUMN secret_encrypted BYTEA;
